#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_vimfiler_filetypeicon = true
    enable_vimfiler_gitstatus = true
    statusline_left_sections = [
      'winnr',
      'filename',
      'version control info',
      'minor mode lighters',
    ]
    statusline_right_sections = [
      'fileformat',
      'major mode',
      'cursorpos',
      'percentage'
    ]
#enable_statusline_mode = true
#statusline_unicode = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    bootstrap_after = "myconfig#after"
    disabled_plugins = ["asynconplete.vim","deoplete.nvim"]

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_enable_snippets_in_popup = false
auto_completion_return_key_behavior = "complte"
auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "ctrlp"

[[layers]]
  name = "github"

[[layers]]
  name = "git"
  git-plugin = "fugitive"

[[layers]]
  name = "VersionControl"
  enable-gtm-status = true

# Custom Plugins
[[custom_plugins]]
repo = "NLKNguyen/papercolor-theme"
merged = 0

[[custom_plugins]]
repo = "liuchengxu/space-vim-dark"
merged = 0

[[custom_plugins]]
repo = "ryanoasis/vim-devicons"
merged = 0

[[custom_plugins]]
repo = "ap/vim-css-color"
merged = 0

[[custom_plugins]]
repo = "kyazdani42/nvim-web-devicons"
merged = 0

[[custom_plugins]]
repo = "frazrepo/vim-rainbow"
merged = 0

[[custom_plugins]]
repo = "tpope/vim-commentary"
merged = 0

[[custom_plugins]]
repo = "vim-python/python-syntax"
merged = 0

[[custom_plugins]]
  name = "dracula/vim"
